version: "3"

services:
  app:
    image: chanyutl/pandoriabox:latest
    container_name: pandoria-gameserver-dev
    volumes:
      - .:/go/src/x10/pandoria/gameserver
      - /var/filebeat_log/unity:/var/log/pandoria
      - /var/filebeat_log/room:/root/.config/unity3d/x10/Pandoria\ Server/Pandoria/temp
    ports:
      - "9002:9002"
      - "9011-9050:9011-9050/udp"
    working_dir: /go/src/x10/pandoria/gameserver
    command: revel run x10/pandoria/gameserver dev

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    container_name: filebeat
    volumes:
    - /var/filebeat_log:/var/filebeat_log
    - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    