filebeat.inputs:
- type: log
  enabled: true
  paths:
  - /var/filebeat_log/unity/*.log
  - /var/filebeat_log/room/*.log
  encoding: utf-8
  multiline.pattern: '^#'
  multiline.negate: true
  multiline.match: after
  multiline.max_lines: 500

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

setup.template.settings:
  index.number_of_shards: 1

output.logstash:
  hosts: ["3.1.202.34:5000"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~