version: "3"
services:
    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        environment:
            - "GF_DEFAULT_INSTANCE_NAME=CSAG-Grafana"
            - "GF_SERVER_ROOT_URL=http://grafana.kmi.tl"
            - "GF_SERVER_ENABLE_GZIP=true"
            - "GF_SECURITY_ADMIN_USER=csag"
            - 'GF_SECURITY_ADMIN_PASSWORD=c$$@g_s3cr3t_p@ss'
            - "GF_INSTALL_PLUGINS=grafana-piechart-panel"
            - "GF_SMTP_ENABLED=true"
            - "GF_SMTP_HOST=smtp.office365.com:587"
            - "GF_SMTP_USER=csag@kmi.tl"
            - "GF_SMTP_PASSWORD=Mona3926"
            - "GF_SMTP_SKIP_VERIFY=true"
            - "GF_SMTP_FROM_ADDRESS=csag@kmi.tl"
            - "GF_SMTP_FROM_NAME=CSAG"
            - "GF_METRICS_ENABLED=false"
        volumes:
            - grafana-storage:/var/lib/grafana
        ports:
            - 3000:3000

volumes:
    grafana-storage:
