version: "3"
services:
    portainer:
        image: portainer/portainer
        container_name: portainer
        restart: always
        ports:
            - 8001:8000
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

volumes:
    portainer_data:
